#
# Makefile for the kernel multimedia device drivers.
#

obj-y += common/ video/

obj-$(CONFIG_VIDEO_DEV)		+= radio/
obj-$(CONFIG_DVB_CORE)  	+= dvb/
obj-$(CONFIG_VIDEO_SAMSUNG)	+= s3c6410/camera/
obj-$(CONFIG_VIDEO_MFC)		+= s3c6410/mfc/
obj-$(CONFIG_VIDEO_PP)		+= s3c6410/pp/
obj-$(CONFIG_VIDEO_JPEG) 	+= s3c6410/jpeg/
obj-$(CONFIG_VIDEO_G3D)     += s3c6410/g3d/
obj-$(CONFIG_VIDEO_G2D)     += s3c6410/g2d/
obj-$(CONFIG_S3C_CMM)       += s3c6410/cmm/
