##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Throughc
##############################################################################
# VERSION&DATE	: Version 1.00	2007/12/25 (Throughc)
##############################################################################


obj-$(CONFIG_ACCEL_KXSD9)	+= kxsd9_2042.o


obj-$(CONFIG_ACCEL_KR3DM)	+= kr3dm_i2c.o


obj-$(CONFIG_ACCEL_BMA020)	+= bma020_i2c.o \
                               bma020.o \
	                           bma020_acc.o

