# arch/arm/mach-s5pc100/Makefile
#
# Copyright 2008 Openmoko, Inc.
# Copyright 2008 Simtec Electronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

# Core support for S5PC100 system

obj-$(CONFIG_CPU_S5PC100)	+= cpu.o

# machine support

obj-$(CONFIG_MACH_SMDKC100)	+= mach-smdkc100.o
