obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_MFC40)	+= mfc40/
obj-$(CONFIG_VIDEO_MFC50)       += mfc50/
obj-$(CONFIG_VIDEO_TV20)	+= tv20_ap/
obj-$(CONFIG_VIDEO_JPEG_V2)	+= jpeg_v2/
obj-$(CONFIG_VIDEO_ROTATOR)	+= rotator/
obj-$(CONFIG_VIDEO_TSI)		+= tsi/
 
EXTRA_CFLAGS += -Idrivers/media/video

