#################################################
# Makefile for Post Processor 
# 2009 (C) Samsung Electronics 
# Author : Jaeryul peter Oh <jaeryul.oh@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_ROTATOR)	+= s3c_rotator.o

EXTRA_CFLAGS += -Idrivers/media/video

